### ISSUE TITLE
Let's use Slack or Discord for Collaboration as opposed to Email

### ISSUE THREAD

**Issue by 1ktribble** [mentzbb/SuggestionBox#1]

**Comment by keirbowden** [comment]
Not sure I understand this - we use chatter to collaborate, the emails are just notifications.

**Comment by 1ktribble** [comment]
Chatter is a fine collaboration tool, but since I work in Salesforce orgs day in and day out, it would be nice to also have a place to share articles, blog posts, YT videos, etc. without having to log into Salesforce to do so.
